version: "3.9"
services:

  # PostgreSQL
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes: 
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # DRS Starter Kit (Postgres)
  docker-postgres:
    build:
      context: .
      dockerfile: Dockerfile-Postgres
      args:
        VERSION: 0.3.2
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
