version: "3.9"
services:

  # PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=starter_kit_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./database/postgresql/create-tables.sql:/docker-entrypoint-initdb.d/1-create-tables.sql"
      - "./database/postgresql/add-dev-dataset.sql:/docker-entrypoint-initdb.d/2-add-dev-dataset.sql"
 
  # DRS
  drs:
    image: ga4gh/ga4gh-starter-kit-drs:0.3.1
    container_name: drs
    ports:
      - "5000:5000" # public
      - "5001:5001" # admin
    volumes:
      - "./src/test/resources/config:/config"
      
    command: -c /config/test-postgres.yml
